version: '3.8'
services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # volumes:
      # - ../../:/workspaces:cached
    # ports:
    #   - "3001:3001"
    depends_on:
      - db
    network_mode: service:db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nomadland
      - POSTGRES_HOST=db  # This should point to the db service
      - POSTGRES_PORT=5432

  db:
    image: postgres:latest
    # ports:
    #   - '5450:5432'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nomadland

volumes:
  postgres-data:
